jobs:
- name: job-upload-release
  plan:
  - get: source-code
    params:
      depth: 1
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      platform: linux
      run:
        path: ./tasks/upload-release.sh
    task: upload-release
  public: true
resources:
- name: source-code
  source:
    branch: master
    uri: git@github.com:byllc/sw-concourse-training.git
  type: git

